2020-11-02 03:17:35,796:DEBUG:certbot._internal.main:certbot version: 1.9.0
2020-11-02 03:17:35,798:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'rpi.iot.2020@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'rpi-iot.duckdns.org']
2020-11-02 03:17:35,798:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-11-02 03:17:35,855:DEBUG:certbot._internal.log:Root logging level set at 20
2020-11-02 03:17:35,856:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-11-02 03:17:35,858:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2020-11-02 03:17:35,872:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f60f95b5cd0>
Prep: True
2020-11-02 03:17:35,873:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f60f95b5cd0> and installer None
2020-11-02 03:17:35,874:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2020-11-02 03:17:35,884:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/101051429', new_authzr_uri=None, terms_of_service=None), 5d3ee078da7cf6246f5d859f4c2f98b7, Meta(creation_dt=datetime.datetime(2020, 11, 2, 3, 13, 29, tzinfo=<UTC>), creation_host='f3cef6fea34b', register_to_eff=None))>
2020-11-02 03:17:35,886:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2020-11-02 03:17:35,890:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2020-11-02 03:17:36,737:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2020-11-02 03:17:36,741:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 03:17:36 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "bBhXE0RH6hA": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-11-02 03:17:36,745:INFO:certbot._internal.main:Obtaining a new certificate
2020-11-02 03:17:37,325:DEBUG:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0002_key-certbot.pem
2020-11-02 03:17:37,334:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0002_csr-certbot.pem
2020-11-02 03:17:37,336:DEBUG:acme.client:Requesting fresh nonce
2020-11-02 03:17:37,336:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2020-11-02 03:17:37,546:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-11-02 03:17:37,547:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 03:17:37 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0103yKZAKMQUXA7bc_HaGDy6s1m0ujPeRRSn7RJWa2TRCIE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-11-02 03:17:37,548:DEBUG:acme.client:Storing nonce: 0103yKZAKMQUXA7bc_HaGDy6s1m0ujPeRRSn7RJWa2TRCIE
2020-11-02 03:17:37,550:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "rpi-iot.duckdns.org"\n    }\n  ]\n}'
2020-11-02 03:17:37,559:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDUxNDI5IiwgIm5vbmNlIjogIjAxMDN5S1pBS01RVVhBN2JjX0hhR0R5NnMxbTB1alBlUlJTbjdSSldhMlRSQ0lFIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "RqYvFxOOVE5rcJJYPLjZ4dSyFFGxRZgGivOc2MMqtXEuEDs7p9Zb0Trk-suFUfmICaFhy77hISFj7ItZqyu4FrM-Va3I5v721QeWlZZcLsCtyoRq8in2am_1wQnSkMd4DvUK-ZmYymMSOcu1zNZtVsKXCjYGF6hAv2p1zEuxeT0M2qoeTYqQJAPFgQH7c0TIWLKIXFuw5HrG61Yre-R7c9GijpMYAOGeBNCWXD5ykwZ22ePbNHMUjhCaMslv9OSRQQX404D0DYzkAK4WOOYWqRtnpFE8TL6RGYHr3y6TCf-8fAjHN7jbzrhBCiYDPh5KrEMmLcMFp04z4Tnoz4o7EQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInJwaS1pb3QuZHVja2Rucy5vcmciCiAgICB9CiAgXQp9"
}
2020-11-02 03:17:38,050:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 350
2020-11-02 03:17:38,055:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Mon, 02 Nov 2020 03:17:37 GMT
Content-Type: application/json
Content-Length: 350
Connection: keep-alive
Boulder-Requester: 101051429
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/101051429/5993183192
Replay-Nonce: 0104bLEOExkSF88-mKxhPCfaQBx4lU0S7hY25nxVgCkMWuU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2020-11-09T03:17:37.820038892Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "rpi-iot.duckdns.org"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8302546289"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/101051429/5993183192"
}
2020-11-02 03:17:38,057:DEBUG:acme.client:Storing nonce: 0104bLEOExkSF88-mKxhPCfaQBx4lU0S7hY25nxVgCkMWuU
2020-11-02 03:17:38,059:DEBUG:acme.client:JWS payload:
b''
2020-11-02 03:17:38,067:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/8302546289:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDUxNDI5IiwgIm5vbmNlIjogIjAxMDRiTEVPRXhrU0Y4OC1tS3hoUENmYVFCeDRsVTBTN2hZMjVueFZnQ2tNV3VVIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My84MzAyNTQ2Mjg5In0",
  "signature": "pVmOCUhPOKmG6JqeJ2Z_c_6xub_T2HWQ8kjeqe1PQ1gIcFJeNv79F40gaPIEHP1Vr6uYBpVhsKPy2N8oXhljeekpHJb5_yDwXHfd4YMfL_duY0UaCeXDSdxsehcQqzxWC6AsrbjN7Pn69KDhFX342oZyJc7zLU_P81SkX5bA2OZ5eWZiRru03qDiX5uq4xMT-_nGY4cE19uKpK1w8Rcl1cMC6Wp8cpPezYKrs43bUcocfAm5Whtjb3_vj0MYGe7dAtjFuy4uuW-krl-8RCgYivSQhqB_80B2TN1jnZDmMgHqT_y070HfaxiAuAoyjSPzXW57jx6i5uBdZIgxMNQ8jw",
  "payload": ""
}
2020-11-02 03:17:38,305:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/8302546289 HTTP/1.1" 200 797
2020-11-02 03:17:38,307:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 03:17:38 GMT
Content-Type: application/json
Content-Length: 797
Connection: keep-alive
Boulder-Requester: 101051429
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0104kQrpDVeOq_5bMGyO9mXPIeUqqsGDb9RX3ySE7be4ewg
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "rpi-iot.duckdns.org"
  },
  "status": "pending",
  "expires": "2020-11-09T03:17:37Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8302546289/gWEccg",
      "token": "vBu5lSD9lVymLY4UO6zNZMW7Rzl32JT9QTY-IvbV35k"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8302546289/qNaqyA",
      "token": "vBu5lSD9lVymLY4UO6zNZMW7Rzl32JT9QTY-IvbV35k"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8302546289/NEx6lA",
      "token": "vBu5lSD9lVymLY4UO6zNZMW7Rzl32JT9QTY-IvbV35k"
    }
  ]
}
2020-11-02 03:17:38,307:DEBUG:acme.client:Storing nonce: 0104kQrpDVeOq_5bMGyO9mXPIeUqqsGDb9RX3ySE7be4ewg
2020-11-02 03:17:38,309:INFO:certbot._internal.auth_handler:Performing the following challenges:
2020-11-02 03:17:38,310:INFO:certbot._internal.auth_handler:http-01 challenge for rpi-iot.duckdns.org
2020-11-02 03:17:38,311:INFO:certbot._internal.plugins.webroot:Using the webroot path /usr/share/nginx/html/letsencrypt for all unmatched domains.
2020-11-02 03:17:38,312:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge
2020-11-02 03:17:38,322:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/vBu5lSD9lVymLY4UO6zNZMW7Rzl32JT9QTY-IvbV35k
2020-11-02 03:17:38,323:INFO:certbot._internal.auth_handler:Waiting for verification...
2020-11-02 03:17:38,323:DEBUG:acme.client:JWS payload:
b'{}'
2020-11-02 03:17:38,331:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/8302546289/gWEccg:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDUxNDI5IiwgIm5vbmNlIjogIjAxMDRrUXJwRFZlT3FfNWJNR3lPOW1YUEllVXFxc0dEYjlSWDN5U0U3YmU0ZXdnIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My84MzAyNTQ2Mjg5L2dXRWNjZyJ9",
  "signature": "X63b9MluQzNmRGNP2HK_jkpDgfldSnOKP8tSdWXOd9NtWb1Z28QcLJHGUcBc1xbjC8TPFUv83H_zzCvOhOF-2Q28zV2xEjRvXTWR6-cRewBPbowh7FK5kgR-gLT0BJeHC9Bhm8y_nMAhvHoiXrvCq1IK9Fk6AJt_SO5Zmnd9PHPQSzH4KVeG5NIGClD0ujiwNygpd5IkZNAMU5pO4bkENbh1KdMTrgj4ZThFipHJ38oD5oHNH3jYGWfI3tvIgx8e66t0_p33TKaia1qjmey-ATkOWsP0f5LQ2099ORhYNH3-z-ZZnZMN-VPEk1shOMb43mA7KoNW-sONUKjYNR_vHw",
  "payload": "e30"
}
2020-11-02 03:17:38,587:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/8302546289/gWEccg HTTP/1.1" 200 185
2020-11-02 03:17:38,589:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 03:17:38 GMT
Content-Type: application/json
Content-Length: 185
Connection: keep-alive
Boulder-Requester: 101051429
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/8302546289>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/8302546289/gWEccg
Replay-Nonce: 0103alUUIcPvxgAH2I6ZsYuzoM9Jn4htXVKrZsUdtJpZ4Ws
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8302546289/gWEccg",
  "token": "vBu5lSD9lVymLY4UO6zNZMW7Rzl32JT9QTY-IvbV35k"
}
2020-11-02 03:17:38,590:DEBUG:acme.client:Storing nonce: 0103alUUIcPvxgAH2I6ZsYuzoM9Jn4htXVKrZsUdtJpZ4Ws
2020-11-02 03:17:39,594:DEBUG:acme.client:JWS payload:
b''
2020-11-02 03:17:39,609:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/8302546289:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDUxNDI5IiwgIm5vbmNlIjogIjAxMDNhbFVVSWNQdnhnQUgySTZac1l1em9NOUpuNGh0WFZLclpzVWR0SnBaNFdzIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My84MzAyNTQ2Mjg5In0",
  "signature": "Km0jcs5-xRlyNmRdRsQ_rBw5apwimTzuLPELt62OTDRFfqaTw3IzSC1HcTV8J7CSK8jyDTI62p8wVJLzSuy_wNQl93dYcUS_bAEQPSi9uiX_gkojlrpY_k1QdBYaSLVFiGBlLBi7uV_rVjp8SALATLe55k_3pevqWcF8W60PuvGrvE47MW2xNnGTAXUX0ldOjnFf7SboM_Hw2-k2erNjlONHBe7YdvsAvrYEWu_o4XgHyKQi3NwPWz14QHOGcSBISa-DPJcZ5TTkMCUa099YmMnNzwms0owaGJXEHKLbPdx-inZYDCvmPz9C_ozl4HtcgnaXhhdxqBR7LtZZAMGepg",
  "payload": ""
}
2020-11-02 03:17:39,847:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/8302546289 HTTP/1.1" 200 982
2020-11-02 03:17:39,849:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 03:17:39 GMT
Content-Type: application/json
Content-Length: 982
Connection: keep-alive
Boulder-Requester: 101051429
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 01044atnyh63-ds1AHEOcBuASS5B_OAfMicdgo0rpDkuJ_4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "rpi-iot.duckdns.org"
  },
  "status": "invalid",
  "expires": "2020-11-09T03:17:37Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "Fetching http://rpi-iot.duckdns.org/.well-known/acme-challenge/vBu5lSD9lVymLY4UO6zNZMW7Rzl32JT9QTY-IvbV35k: Connection refused",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8302546289/gWEccg",
      "token": "vBu5lSD9lVymLY4UO6zNZMW7Rzl32JT9QTY-IvbV35k",
      "validationRecord": [
        {
          "url": "http://rpi-iot.duckdns.org/.well-known/acme-challenge/vBu5lSD9lVymLY4UO6zNZMW7Rzl32JT9QTY-IvbV35k",
          "hostname": "rpi-iot.duckdns.org",
          "port": "80",
          "addressesResolved": [
            "60.53.241.89"
          ],
          "addressUsed": "60.53.241.89"
        }
      ]
    }
  ]
}
2020-11-02 03:17:39,849:DEBUG:acme.client:Storing nonce: 01044atnyh63-ds1AHEOcBuASS5B_OAfMicdgo0rpDkuJ_4
2020-11-02 03:17:39,850:WARNING:certbot._internal.auth_handler:Challenge failed for domain rpi-iot.duckdns.org
2020-11-02 03:17:39,851:INFO:certbot._internal.auth_handler:http-01 challenge for rpi-iot.duckdns.org
2020-11-02 03:17:39,852:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: rpi-iot.duckdns.org
Type:   connection
Detail: Fetching http://rpi-iot.duckdns.org/.well-known/acme-challenge/vBu5lSD9lVymLY4UO6zNZMW7Rzl32JT9QTY-IvbV35k: Connection refused

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
2020-11-02 03:17:39,853:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2020-11-02 03:17:39,854:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-11-02 03:17:39,854:INFO:certbot._internal.auth_handler:Cleaning up challenges
2020-11-02 03:17:39,854:DEBUG:certbot._internal.plugins.webroot:Removing /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/vBu5lSD9lVymLY4UO6zNZMW7Rzl32JT9QTY-IvbV35k
2020-11-02 03:17:39,855:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2020-11-02 03:17:39,856:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1362, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1243, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 122, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 418, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 351, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 398, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2020-11-02 03:17:39,859:ERROR:certbot._internal.log:Some challenges have failed.
